
# validation

- name: assert all vars are set
  assert: 
    that: "{{ item }} != '' " 
    quiet: true
  with_items:
  - app_name
  - installation_folder


# required dependencies

- name: make sure epel-release is installed
  yum:
    name: epel-release
    state: present
    lock_timeout: 180
  become: yes

- name: make sure rsync is installed
  yum:
    name: rsync
    state: present
    lock_timeout: 180
  become: yes

- name: make sure unzip is installed
  yum:
    name: unzip
    state: present
    lock_timeout: 180
  become: yes


# disable selinux and firewalld

- name: disable selinux
  selinux:
    state: disabled
  become: yes
   
# set temp folder

- name: make sure temp folder
  file:
    path: "{{ temp_folder }}"
    state: directory
    owner: "{{ ansible_user_id }}"
  become: yes

# download the file

- name: download zip from s3 url
  get_url:
    url: "{{ s3_download_url }}"
    dest: "{{ temp_folder }}/{{ installer_file_name }}"
    timeout: "{{ download_timeout | default(60) }}"
  when: custom_download_url == ""

- name: download zip from custom url
  get_url:
    url: "{{ custom_download_url }}"
    dest: "{{ temp_folder }}/{{ installer_file_name }}"
    timeout: "{{ download_timeout | default(60) }}"
  when: custom_download_url != ""
